create table if not exists public.branches (
  id integer generated by default as identity primary key,
  name text not null unique,
  phone text,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.designers (
  id integer generated by default as identity primary key,
  branch_id integer not null references public.branches(id) on delete restrict,
  name text not null,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.templates (
  id integer generated by default as identity primary key,
  branch_id integer references public.branches(id) on delete restrict,
  name text not null,
  description text,
  content text not null,
  bizgo_template_code text,
  bizgo_sender_key text,
  bizgo_message text,
  bizgo_button_name text,
  is_active boolean not null default true,
  deleted_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.notification_templates (
  id integer generated by default as identity primary key,
  branch_id integer not null references public.branches(id) on delete restrict,
  description text,
  sender_key text not null,
  sender_key_type text not null default 'S',
  template_code text not null,
  template_name text not null,
  template_message_type text not null default 'BA',
  template_emphasize_type text not null default 'NONE',
  category_code text,
  security_flag boolean not null default false,
  message text not null,
  title text,
  subtitle text,
  header text,
  button_name text,
  button_type text,
  button_url_mobile text,
  button_url_pc text,
  button_scheme_ios text,
  button_scheme_android text,
  button_tel_number text,
  inspection_status text,
  remote_block boolean not null default false,
  remote_dormant boolean not null default false,
  remote_created_at text,
  remote_modified_at text,
  remote_payload jsonb,
  last_synced_at timestamptz,
  is_active boolean not null default true,
  deleted_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.documents (
  id integer generated by default as identity primary key,
  token text not null unique,
  template_id integer not null references public.templates(id) on delete restrict,
  notification_template_id integer references public.notification_templates(id) on delete restrict,
  branch_id integer references public.branches(id) on delete restrict,
  designer_id integer references public.designers(id) on delete restrict,
  branch_name text not null,
  document_title text not null,
  document_date date not null,
  customer_name text not null,
  phone_last4 text not null check (phone_last4 ~ '^[0-9]{4}$'),
  recipient_phone text,
  designer_name text not null,
  notification_template_name text,
  rendered_content text not null,
  status text not null default 'pending',
  viewed_at timestamptz,
  signed_at timestamptz,
  signature_data_url text,
  bizgo_status text,
  bizgo_response jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.admin_users (
  id integer generated by default as identity primary key,
  kakao_user_id text not null unique,
  branch_id integer references public.branches(id) on delete restrict,
  nickname text,
  memo text,
  role text not null default 'admin',
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.login_attempts (
  id integer generated by default as identity primary key,
  kakao_user_id text not null unique,
  nickname text,
  attempt_count integer not null default 1,
  last_status text not null default 'blocked',
  first_attempt_at timestamptz not null default timezone('utc', now()),
  last_attempt_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.login_attempt_logs (
  id bigint generated by default as identity primary key,
  kakao_user_id text not null,
  nickname text,
  status text not null default 'blocked',
  attempted_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.sessions (
  id integer generated by default as identity primary key,
  session_token text not null unique,
  kakao_user_id text not null,
  branch_id integer references public.branches(id) on delete set null,
  nickname text,
  role text not null default 'admin',
  is_master boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  expires_at timestamptz not null
);

alter table public.templates add column if not exists branch_id integer references public.branches(id) on delete restrict;
alter table public.templates add column if not exists deleted_at timestamptz;
alter table public.branches add column if not exists phone text;
alter table public.notification_templates add column if not exists branch_id integer references public.branches(id) on delete restrict;
alter table public.notification_templates add column if not exists description text;
alter table public.notification_templates add column if not exists sender_key text;
alter table public.notification_templates add column if not exists sender_key_type text default 'S';
alter table public.notification_templates add column if not exists template_code text;
alter table public.notification_templates add column if not exists template_name text;
alter table public.notification_templates add column if not exists template_message_type text default 'BA';
alter table public.notification_templates add column if not exists template_emphasize_type text default 'NONE';
alter table public.notification_templates add column if not exists category_code text;
alter table public.notification_templates add column if not exists security_flag boolean default false;
alter table public.notification_templates add column if not exists message text;
alter table public.notification_templates add column if not exists title text;
alter table public.notification_templates add column if not exists subtitle text;
alter table public.notification_templates add column if not exists header text;
alter table public.notification_templates add column if not exists button_name text;
alter table public.notification_templates add column if not exists button_type text;
alter table public.notification_templates add column if not exists button_url_mobile text;
alter table public.notification_templates add column if not exists button_url_pc text;
alter table public.notification_templates add column if not exists button_scheme_ios text;
alter table public.notification_templates add column if not exists button_scheme_android text;
alter table public.notification_templates add column if not exists button_tel_number text;
alter table public.notification_templates add column if not exists inspection_status text;
alter table public.notification_templates add column if not exists remote_block boolean default false;
alter table public.notification_templates add column if not exists remote_dormant boolean default false;
alter table public.notification_templates add column if not exists remote_created_at text;
alter table public.notification_templates add column if not exists remote_modified_at text;
alter table public.notification_templates add column if not exists remote_payload jsonb;
alter table public.notification_templates add column if not exists last_synced_at timestamptz;
alter table public.notification_templates add column if not exists is_active boolean default true;
alter table public.notification_templates add column if not exists deleted_at timestamptz;
alter table public.documents add column if not exists branch_id integer references public.branches(id) on delete restrict;
alter table public.documents add column if not exists designer_id integer references public.designers(id) on delete restrict;
alter table public.documents add column if not exists notification_template_id integer references public.notification_templates(id) on delete restrict;
alter table public.documents add column if not exists notification_template_name text;
alter table public.admin_users add column if not exists branch_id integer references public.branches(id) on delete restrict;
alter table public.admin_users add column if not exists role text default 'admin';
alter table public.sessions add column if not exists branch_id integer references public.branches(id) on delete set null;
alter table public.sessions add column if not exists role text default 'admin';
alter table public.sessions add column if not exists is_master boolean default false;

create unique index if not exists designers_branch_id_name_key on public.designers(branch_id, name);
create index if not exists templates_branch_id_idx on public.templates(branch_id);
create index if not exists templates_deleted_at_idx on public.templates(deleted_at);
create unique index if not exists notification_templates_branch_sender_code_key on public.notification_templates(branch_id, sender_key, template_code);
create index if not exists notification_templates_branch_id_idx on public.notification_templates(branch_id);
create index if not exists notification_templates_deleted_at_idx on public.notification_templates(deleted_at);
create index if not exists documents_branch_id_idx on public.documents(branch_id);
create index if not exists documents_designer_id_idx on public.documents(designer_id);
create index if not exists documents_template_id_idx on public.documents(template_id);
create index if not exists documents_notification_template_id_idx on public.documents(notification_template_id);
create index if not exists documents_created_at_idx on public.documents(created_at desc);
create index if not exists admin_users_branch_id_idx on public.admin_users(branch_id);
create index if not exists admin_users_kakao_user_id_idx on public.admin_users(kakao_user_id);
create index if not exists login_attempts_last_attempt_at_idx on public.login_attempts(last_attempt_at desc);
create index if not exists login_attempt_logs_attempted_at_idx on public.login_attempt_logs(attempted_at desc);
create index if not exists login_attempt_logs_kakao_user_id_idx on public.login_attempt_logs(kakao_user_id);
create index if not exists sessions_expires_at_idx on public.sessions(expires_at);

alter table public.branches enable row level security;
alter table public.designers enable row level security;
alter table public.templates enable row level security;
alter table public.notification_templates enable row level security;
alter table public.documents enable row level security;
alter table public.admin_users enable row level security;
alter table public.login_attempts enable row level security;
alter table public.login_attempt_logs enable row level security;
alter table public.sessions enable row level security;
