begin;

drop table if exists public.sessions cascade;
drop table if exists public.login_attempt_logs cascade;
drop table if exists public.login_attempts cascade;
drop table if exists public.admin_users cascade;
drop table if exists public.documents cascade;
drop table if exists public.notification_templates cascade;
drop table if exists public.templates cascade;
drop table if exists public.designers cascade;
drop table if exists public.branches cascade;

create table public.branches (
  id integer generated by default as identity primary key,
  name text not null unique,
  phone text,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table public.designers (
  id integer generated by default as identity primary key,
  branch_id integer not null references public.branches(id) on delete restrict,
  name text not null,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (branch_id, name)
);

create table public.templates (
  id integer generated by default as identity primary key,
  name text not null,
  document_title text not null,
  content text not null,
  is_active boolean not null default true,
  deleted_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table public.notification_templates (
  id integer generated by default as identity primary key,
  sender_key text not null,
  sender_key_type text not null default 'S',
  template_code text not null,
  template_name text not null,
  template_message_type text not null default 'BA',
  template_emphasize_type text not null default 'NONE',
  category_code text,
  security_flag boolean not null default false,
  message text not null,
  title text,
  subtitle text,
  header text,
  button_name text,
  button_type text,
  button_url_mobile text,
  button_url_pc text,
  button_scheme_ios text,
  button_scheme_android text,
  button_tel_number text,
  inspection_status text,
  remote_block boolean not null default false,
  remote_dormant boolean not null default false,
  remote_created_at text,
  remote_modified_at text,
  remote_payload jsonb,
  last_synced_at timestamptz,
  is_active boolean not null default true,
  deleted_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (sender_key, template_code)
);

create table public.documents (
  id integer generated by default as identity primary key,
  token text not null unique,
  template_id integer not null references public.templates(id) on delete restrict,
  notification_template_id integer references public.notification_templates(id) on delete restrict,
  branch_id integer not null references public.branches(id) on delete restrict,
  designer_id integer not null references public.designers(id) on delete restrict,
  branch_name text not null,
  document_title text not null,
  document_date date not null,
  customer_name text not null,
  phone_last4 text not null check (phone_last4 ~ '^[0-9]{4}$'),
  recipient_phone text,
  designer_name text not null,
  notification_template_name text,
  rendered_content text not null,
  status text not null default 'pending' check (status in ('pending', 'signed', 'failed')),
  viewed_at timestamptz,
  signed_at timestamptz,
  signature_data_url text,
  bizgo_status text,
  bizgo_response jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table public.admin_users (
  id integer generated by default as identity primary key,
  kakao_user_id text not null unique,
  branch_id integer references public.branches(id) on delete restrict,
  nickname text,
  memo text,
  role text not null check (role in ('integrated_master', 'branch_master', 'admin')),
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint admin_users_role_branch_check check (
    (role = 'integrated_master' and branch_id is null)
    or
    (role in ('branch_master', 'admin') and branch_id is not null)
  )
);

create table public.login_attempts (
  id integer generated by default as identity primary key,
  kakao_user_id text not null unique,
  nickname text,
  attempt_count integer not null default 1,
  last_status text not null default 'blocked',
  first_attempt_at timestamptz not null default timezone('utc', now()),
  last_attempt_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table public.login_attempt_logs (
  id bigint generated by default as identity primary key,
  kakao_user_id text not null,
  nickname text,
  status text not null default 'blocked',
  attempted_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now())
);

create table public.sessions (
  id integer generated by default as identity primary key,
  session_token text not null unique,
  kakao_user_id text not null,
  branch_id integer references public.branches(id) on delete set null,
  nickname text,
  role text not null check (role in ('integrated_master', 'branch_master', 'admin')),
  is_master boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  expires_at timestamptz not null,
  constraint sessions_role_branch_check check (
    (role = 'integrated_master' and branch_id is null)
    or
    (role in ('branch_master', 'admin') and branch_id is not null)
  )
);

create index designers_branch_id_idx on public.designers(branch_id);
create index templates_deleted_at_idx on public.templates(deleted_at);
create index notification_templates_deleted_at_idx on public.notification_templates(deleted_at);
create index documents_branch_id_idx on public.documents(branch_id);
create index documents_designer_id_idx on public.documents(designer_id);
create index documents_template_id_idx on public.documents(template_id);
create index documents_notification_template_id_idx on public.documents(notification_template_id);
create index documents_created_at_idx on public.documents(created_at desc);
create index admin_users_branch_id_idx on public.admin_users(branch_id);
create index admin_users_kakao_user_id_idx on public.admin_users(kakao_user_id);
create index login_attempts_last_attempt_at_idx on public.login_attempts(last_attempt_at desc);
create index login_attempt_logs_attempted_at_idx on public.login_attempt_logs(attempted_at desc);
create index login_attempt_logs_kakao_user_id_idx on public.login_attempt_logs(kakao_user_id);
create index sessions_expires_at_idx on public.sessions(expires_at);

alter table public.branches enable row level security;
alter table public.designers enable row level security;
alter table public.templates enable row level security;
alter table public.notification_templates enable row level security;
alter table public.documents enable row level security;
alter table public.admin_users enable row level security;
alter table public.login_attempts enable row level security;
alter table public.login_attempt_logs enable row level security;
alter table public.sessions enable row level security;

commit;
