create table if not exists public.notification_templates (
  id integer generated by default as identity primary key,
  branch_id integer not null references public.branches(id) on delete restrict,
  description text,
  sender_key text not null,
  sender_key_type text not null default 'S',
  template_code text not null,
  template_name text not null,
  template_message_type text not null default 'BA',
  template_emphasize_type text not null default 'NONE',
  category_code text,
  security_flag boolean not null default false,
  message text not null,
  title text,
  subtitle text,
  header text,
  button_name text,
  button_type text,
  button_url_mobile text,
  button_url_pc text,
  button_scheme_ios text,
  button_scheme_android text,
  button_tel_number text,
  inspection_status text,
  remote_block boolean not null default false,
  remote_dormant boolean not null default false,
  remote_created_at text,
  remote_modified_at text,
  remote_payload jsonb,
  last_synced_at timestamptz,
  is_active boolean not null default true,
  deleted_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.documents
  add column if not exists notification_template_id integer references public.notification_templates(id) on delete restrict;

alter table public.documents
  add column if not exists notification_template_name text;

create unique index if not exists notification_templates_branch_sender_code_key
  on public.notification_templates(branch_id, sender_key, template_code);

create index if not exists notification_templates_branch_id_idx
  on public.notification_templates(branch_id);

create index if not exists notification_templates_deleted_at_idx
  on public.notification_templates(deleted_at);

create index if not exists documents_notification_template_id_idx
  on public.documents(notification_template_id);

alter table public.notification_templates enable row level security;
